version: '3.8'

services:
  cep-temperatura:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
      - HOST=${HOST:-0.0.0.0}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_BASE_URL=${WEATHER_BASE_URL:-http://api.weatherapi.com/v1}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
