server:
  port: "8080"
  host: "0.0.0.0"

weather:
  api_key: "${WEATHER_API_KEY}"
  base_url: "http://api.weatherapi.com/v1"

database:
  host: "${DB_HOST:-localhost}"
  port: 5432
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_DATABASE:-cep_temperatura}"
